
version: 2

models:
  - name: stats.sql
    description: "contracts file"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  